server:
  port: 8080
  servlet:
    context-path: /demoTest

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demotest1
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
jwt:
  signerKey: bvkfSG5tgcc6kHcMWz6VpgyEjCmg16w8EzZv5mPs3KT4Tt1lS3AhkkOBE3oabTJ8
  vaild-duration: 1800
  refresh-duration: 86400