server:
  port: 8080
  servlet:
    context-path: /demoTest

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demotest1
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenquanglinh0509@gmail.com
    password: aoou cjxq wgoi qsrz
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true # format SQL cho dễ đọc
    # open-in-view: false  # tránh warning + tốt cho REST API
    # database-platform: org.hibernate.dialect.MySQL8Dialect
  ai:
    openai:
      api-key: AIzaSyCWas065xHWpQs3o643GB85EtZb3t_ib_s
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemini-2.0-flash
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

image:
  upload-dir: D:\hocJava\demotest\upload

jwt:
  signerKey: API_KEY
  vaild-duration: 18000
  refresh-duration: 86400
logging:
  level:
    spring:
      apo:
        demotest: DEBUG
